# drone 本地构建
kind: pipeline
type: docker
name: story-map

# drone执行触发器
trigger:
  branch:
    - main

volumes:
  - name: cache
    host:
      path: /root

# drone构建步骤
steps:
  - name: node
    pull: if-not-exists
    image: node
    commands:
      - npm install
      - npm run build
  # 1.打成docker
  - name: forntend-build
    pull: if-not-exists
    image: plugins/docker
    settings:
      username: 571863559@qq.com
      password:
        from_secret: DOCKER_PWD
      registry: ghcr.io
      repo: ghcr.io/dawnsouther/0moe-story-map
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
      dockerfile: docker/frontend/Dockerfile
  - name: server-build
    pull: if-not-exists
    image: plugins/docker
    settings:
      username: 571863559@qq.com
      password:
        from_secret: DOCKER_PWD
      registry: ghcr.io
      repo: ghcr.io/dawnsouther/0moe-story-map-server
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
      dockerfile: docker/server/Dockerfile
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 122.51.158.110
      username: root
      port: 22
      password:
        from_secret: SSH_PWD
      script:
        - cd /0moe
        - docker-compose pull story-map story-map-server
        - docker-compose up -d story-map story-map-server
        - echo "Deploy Success!"
  # 3.邮件通知
  - name: notice
    pull: if-not-exists
    image: drillster/drone-email
    settings:
      host: smtp.exmail.qq.com
      port: 465
      username: system@0moe.cn
      password: 7jtFDPkTmnDbbEQA
      from: system@0moe.cn
      recipients_only: true
      recipients:
       - 571863559@qq.com
    when:
      status: [failure, success]
